### ISSUE TITLE
[Model | Entities] User Entity

### ISSUE THREAD

**Issue by Jacob4649** [CSC207-2022F-UofT/course-project-team-java-help#9]
Entity for a user. Could perhaps include a separate password information class. A user entity represents the complete information of that user account, as well as its logistics and authentication information.

**Comment by Lam207** [comment]
Hey Team (especially Johnny), I'm planning to do UserFactory (for both Client and Provider) and UserQueryConstraint, is it going to overlap your work, though? Let me know if I overlap yours.

**Comment by Jacob4649** [comment]
> Hey Team (especially Johnny), I'm planning to do UserFactory (for both Client and Provider) and UserQueryConstraint, is it going to overlap your work, though? Let me know if I overlap yours. 

`UserQueryConstraint` and `UserFactory` may be outside the scope of this issue.

**Comment by Lam207** [comment]
Oh, I see ``UserQueryConstraint`` is about filtering. Thanks! and ``UserFactory`` too?
